loki:
  auth_enabled: false
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 2
  storage:
    bucketNames:
      admin: admin
      chunks: loki.planetariumhq.com
      ruler: ruler
    type: s3
  schema_config:
    configs:
    - from: "2022-01-11"
      index:
        period: 24h
        prefix: loki_index_
      store: boltdb-shipper
      object_store: s3
      schema: v12

  querier:
    max_concurrent: 32

  query_range:
    parallelise_shardable_queries: true
    align_queries_with_step: true
    cache_config:
      embedded_cache:
        enabled: true
        max_size_mb: 2048
        ttl: 1hr

  query_scheduler:
    max_outstanding_requests_per_tenant: 8192

  limits_config:
    enforce_metric_name: false
    max_query_parallelism: 32
    max_query_series: 1000000
    max_entries_limit_per_query: 100000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 360h
    split_queries_by_interval: 60m
    query_timeout: 600s
    ingestion_rate_mb: 128
    ingestion_burst_size_mb: 140
    per_stream_rate_limit: 128MB
    per_stream_rate_limit_burst: 140MB

  ingester:
    concurrent_flushes: 32
    chunk_block_size: 1310720
    chunk_target_size: 15728640
    index_shards: 32

  server:
    grpc_listen_port: 9095
    grpc_server_max_recv_msg_size: 160388078
    grpc_server_max_send_msg_size: 160388078
    grpc_server_max_concurrent_streams: 0
    http_listen_port: 3100
    http_server_read_timeout: 600s
    http_server_write_timeout: 600s

  frontend:
    max_outstanding_per_tenant: 8192
    scheduler_worker_concurrency: 32

  frontend_worker:
    parallelism: 32
    match_max_concurrent: false

  storage_config:
    aws:
      insecure: false
      s3: s3://us-east-2/loki.planetariumhq.com
      s3forcepathstyle: true
    boltdb_shipper:
      active_index_directory: /var/loki/index
      shared_store: s3

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::319679068466:role/eks-9c-main-loki"

write:
  replicas: 3
  nodeSelector:
    alpha.eksctl.io/nodegroup-name: 9c-main-r6g-xl
  resources:
    requests:
      cpu: 1500m
      memory: 6Gi
    
read:
  replicas: 7
  nodeSelector:
    alpha.eksctl.io/nodegroup-name: 9c-main-r6g-xl
  resources:
    requests:
      cpu: 1500m
      memory: 10Gi
    limits:
      cpu: 1500m
      memory: 10Gi

test:
  enabled: false
monitoring:
  lokiCanary:
    enabled: false
  dashboards:
    enabled: false
  rules:
    enabled: false
  alerts:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false

    grafanaAgent:
      installOperator: false
