apiVersion: v1
data:
  APP_PROTOCOL_VERSION: 1118/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCICDxd1O2aFSOExeg096Q9ZUCGvpourUgC.fLrwExA.PVAiA4skPsARy0ocHUhSNOLDBuuutxzDnlpFXDCwnVmNBUeA==/ZHU4OmxhdW5jaGVydTQyOjEvNGQwNTNjYWIzODdhNmQ4NWQ3MGFkYmRmMTcwYjEwOTI3ZTE1MDcxOHU2OnBsYXllcnU0MjoxLzcyMDNlOTAyZWE4NWYwYTg3ZDg3YThiMWMxYzUwNjhkODFjNjdmZjN1OTp0aW1lc3RhbXB1MTA6MjAyMi0xMC0xOWU=
kind: ConfigMap
metadata:
  name: version-config
