images:
- name: kustomization-libplanet-seed
  newName: planetariumhq/libplanet-seed
  newTag: git-c984fa6e98016527e95fe9b50c39a2bf247bcfb6
- name: kustomization-ninechronicles-headless
  newName: planetariumhq/ninechronicles-headless
# PoW
# newTag: git-ea9954a841ddda079d37b7bb0a280b5ca6a2fec4-mk2
# PBFT
  newTag: git-2d469aaf156bdce4ae7413e02457606654bdee7b
- name: kustomization-ninechronicles-dataprovider
  newName: planetariumhq/ninechronicles-dataprovider
  newTag: git-609a7b1e07f7a5dfea2af25aea7a9682dc5292ac
- name: kustomization-ninechronicles-snapshot
  newName: planetariumhq/ninechronicles-snapshot
  newTag: git-88212493c8d4d7a5cbb7e597a2876cea34b56ac2-dynamic
resources:
 - explorer.yaml
 - validator-1.yaml
 - validator-2.yaml
 - validator-3.yaml
 - validator-4.yaml
 - validator-5.yaml
#  - validator-6.yaml
#  - validator-7.yaml
#  - validator-8.yaml
#  - validator-9.yaml
#  - validator-10.yaml
#  - validator-11.yaml
#  - validator-12.yaml
 - remote-headless-1.yaml
 - snapshot.yaml
 - seed.yaml
#  - seed-pow.yaml
