apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: internal-validator-2
  name: internal-validator-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-validator-2
  serviceName: internal-validator-2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: internal-validator-2
    spec:
      initContainers:
      - args:
        - https://9c-snapshot-dev.s3.us-east-2.amazonaws.com/9c-pbft-internal
        - /data/validator
        - $(RESET_SNAPSHOT_OPTION)
        - internal-validator-2
        - $(SLACK_TOKEN)
        command:
        - /bin/download_snapshot.sh
        image: bash:latest
        name: reset-snapshot
        volumeMounts:
        - name: script-volume
          mountPath: /bin/download_snapshot.sh
          readOnly: true
          subPath: download_snapshot.sh
        - mountPath: /data
          name: validator-2-data
        env:
        - name: RESET_SNAPSHOT_OPTION
          valueFrom:
            configMapKeyRef:
              name: reset-snapshot-option
              key: RESET_SNAPSHOT_OPTION
        - name: SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack
              key: token
      containers:
      - args:
        - NineChronicles.Headless.Executable.dll
        - run
        - --app-protocol-version
        - $(APP_PROTOCOL_VERSION_KEY)
        - --store-path=/data/validator
        - --swarm-private-key
        - $(PRIVATE_KEY)
        - --graphql-server
        - --graphql-port=80
        - --host=pbft-validator-2.libpla.net
        - --miner-private-key
        - $(PRIVATE_KEY)
        - --consensus-port=6000
        - --consensus-private-key
        - $(PRIVATE_KEY)
        - --config-path=https://9c-dev-cluster-configs.s3.ap-northeast-2.amazonaws.com/9c-pbft-internal-3.validator.appsettings.json
        command:
        - dotnet
        image: kustomization-ninechronicles-headless
        imagePullPolicy: IfNotPresent
        env:
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: validator-keys
              key: validator2
        - name: APP_PROTOCOL_VERSION_KEY
          valueFrom:
            configMapKeyRef:
              name: version-config
              key: APP_PROTOCOL_VERSION
        name: internal-validator-2
        ports:
        - containerPort: 80
          name: graphql
          protocol: TCP
        - containerPort: 6000
          name: gossip
          protocol: TCP
        - containerPort: 31234
          name: swarm
          protocol: TCP
        resources:
          requests:
            cpu: 1500m
            memory: 6Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: validator-2-data
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: acr-regcred
      nodeSelector:
        node.kubernetes.io/instance-type: m6g.xlarge
      restartPolicy: Always
      volumes:
      - name: script-volume
        configMap:
          defaultMode: 0700
          name: snapshot-script
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: validator-2-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          cpu: 1500m
          memory: 4Gi
          storage: 100Gi
      storageClassName: gp2-extensible-us-east-2c
      volumeMode: Filesystem
