apiVersion: batch/v1
kind: CronJob
metadata:
  name: snapshot-partition-reset
  namespace: default
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - args:
            - s3://9c-snapshots/main/partition/
            - s3://9c-snapshots/main/temp/partition/
            - $(SLACK_TOKEN)
            - $(CF_DISTRIBUTION_ID)
            command:
            - /bin/replace_snapshot.sh
            image: nginx
            name: replace-snapshot
            volumeMounts:
            - mountPath: /bin/replace_snapshot.sh
              name: snapshot-script-partition-reset
              readOnly: true
              subPath: replace_snapshot.sh
            - mountPath: /data
              name: snapshot-volume-full
            - mountPath: /secret
              name: aws-keys
              readOnly: true
            env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-token
                  key: token
            - name: CF_DISTRIBUTION_ID
              valueFrom:
                secretKeyRef:
                  name: aws-keys
                  key: cf_distribution_id
          initContainers:
          - args:
            - temp
            - $(APP_PROTOCOL_VERSION_KEY)
            - $(SLACK_TOKEN)
            - $(CF_DISTRIBUTION_ID)
            command:
            - /bin/upload_snapshot.sh
            image: planetariumhq/ninechronicles-snapshot:git-9af8f34a244a3c1ce1bcd16d12cf61807319b8d7
            name: upload-snapshot1
            volumeMounts:
            - mountPath: /bin/upload_snapshot.sh
              name: snapshot-script-partition-reset
              readOnly: true
              subPath: upload_snapshot.sh
            - mountPath: /data
              name: snapshot-volume-full
            - mountPath: /secret
              name: aws-keys
              readOnly: true
            env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-token
                  key: token
            - name: APP_PROTOCOL_VERSION_KEY
              valueFrom:
                configMapKeyRef:
                  name: version-config
                  key: APP_PROTOCOL_VERSION
            - name: CF_DISTRIBUTION_ID
              valueFrom:
                secretKeyRef:
                  name: aws-keys
                  key: cf_distribution_id
          - args:
            - temp
            - $(APP_PROTOCOL_VERSION_KEY)
            - $(SLACK_TOKEN)
            - $(CF_DISTRIBUTION_ID)
            command:
            - /bin/upload_snapshot.sh
            image: planetariumhq/ninechronicles-snapshot:git-9af8f34a244a3c1ce1bcd16d12cf61807319b8d7
            name: upload-snapshot2
            volumeMounts:
            - mountPath: /bin/upload_snapshot.sh
              name: snapshot-script-partition-reset
              readOnly: true
              subPath: upload_snapshot.sh
            - mountPath: /data
              name: snapshot-volume-full
            - mountPath: /secret
              name: aws-keys
              readOnly: true
            env:
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-token
                  key: token
            - name: APP_PROTOCOL_VERSION_KEY
              valueFrom:
                configMapKeyRef:
                  name: version-config
                  key: APP_PROTOCOL_VERSION
            - name: CF_DISTRIBUTION_ID
              valueFrom:
                secretKeyRef:
                  name: aws-keys
                  key: cf_distribution_id
          nodeSelector:
            alpha.eksctl.io/nodegroup-name: 9c-main-xl
            beta.kubernetes.io/os: linux
          restartPolicy: OnFailure
          volumes:
          - configMap:
              defaultMode: 448
              name: snapshot-script-partition-reset
            name: snapshot-script-partition-reset
          - name: snapshot-volume-full
            persistentVolumeClaim:
              claimName: snapshot-volume-full
          - name: aws-keys
            secret:
              secretName: aws-keys
  schedule: 0 3 1,15 * *
  successfulJobsHistoryLimit: 1
